// ----------------------------------------------------------------------
// Copyright 2022 Schlumberger. All rights reserved in Schlumberger
// authored and generated code (including the selection and
// arrangement of the source code base regardless of the authorship
// of individual files), but not including any copyright interest(s)
// owned by a third party related to source code or object code
// authored or generated by non-Schlumberger personnel.
//
// This source code includes Schlumberger confidential and/or
// proprietary information and may include Schlumberger trade secrets.
// Any use, disclosure and/or reproduction is prohibited unless
// authorized in writing.
//
// Publication Rights :: Schlumberger Private
// ----------------------------------------------------------------------
package peach

import "time"

func CurrentTime() time.Time { return time.Now() }
